### ISSUE TITLE
tutorial 1

### ISSUE THREAD

**Issue by sivammt** [guihomework/dexterous-manipulation-tutorial#1] opened 2015-02-11 07:50 UTC
After launching the created configuration file (tutorial 1-part 1)using "roslaunch moveit_hand_config demo.launch" I am unable to visualize the interact mark on the finger tip in the moveit.rviz window. And when you create the group for Shadow Hand there are joints, links and chain. what should I declare within the chain? kindly suggest me a solution for this
![screenshot from 2015-02-11 08 49 10](https://cloud.githubusercontent.com/assets/10954679/6143545/f2767550-b1ca-11e4-920b-39bd86816ffa.png)

**Comment by guihomework** [comment] 2015-02-12 09:12
I can see on the screenshot you have a biotac hand. Which xacro or urdf file did you use so that I can try reproduce the behavior ?
 The biotac have less joints, and hence the kdl_coupling solver should not be used (never tested as it is for coupled joints and not for fixed joints). A standard KDL solver might work, use the position_only_ik: true config option.

As a generic answer, when you want to control the end-effector, here a finger tip, a chain must be declared with base_link and tip_link. Depending on which IK solver you use, the base might be different. kdl_coupling solver was designed to solve from palm to tips. the KDL standard solver works best for a number of DOF >= 6 but can solve from other base links than the palm then.

**Comment by sivammt** [comment] 2015-02-12 11:30
Hi
Thanks for your reply.
I am using 'shadowhand_motor_biotac.urdf.xacro' file available at the path '/opt/ros/hydro/share/sr_description/robots/' as mentioned in the tutorial. I am using ros-hydro and the sr-hand and moveit packages for the hydro version. 
You may download the exact urdf xacro file that I am using from this link if you wish: http://expirebox.com/download/2e5bd7b1d4acba36aaedf5812c932e1f.html

your comments about the solvers also are really going to be useful and important to know, but right now I did not reach that far. I am still struggling to finish the first tutorial and make some simple interactions by using the interaction marker which I could not get to show up in the rviz window. 
However, I am able to move the hand with random start and goal states in the planning tab.

**Comment by guihomework** [comment] 2015-02-12 15:02
I need to first find a hydro version to test that biotac hand there. You could also provide the urdf (expand urdf.xacro with xacro.py )+ srdf and kinematics.yaml generated by moveit assistant so that I can look at it. 
The markers appear if you select the correct group, that has a chain and an end-effector created accordingly. 
I followed the tutorial in indigo and created a single first_finger group with a chain from palm to fftip with biotac hand model and got the marker displayed. It might be possible that the urdf was upgraded in indigo. This is hard to say without testing or looking at files.

**Comment by sivammt** [comment] 2015-02-13 16:28
http://expirebox.com/download/0b2b4e604651e6876d778bf8ef23f61b.html this is kinematics file and i couldn't find any data inside the file except { } . 
http://expirebox.com/download/fab5b33e60f604a46d1d7b93749510fc.html is the .srdf file generated by moveit setup assistant
 I will follow the same procedures in ROS Indigo and check if it works.

**Comment by guihomework** [comment] 2015-02-16 17:08
This is not normal that the kinematics.yaml is empty. Also the srdf has finger groups with all three link + joint + chain definition. Usually joints and chain is sufficient, or chain and links.  
for an unknown reason one screenshot showing the IK solver setting dropped out of the tutorial. I re-added it 
here it is  ![image](https://raw.github.com/guihomework/dexterous-manipulation-tutorial/master/resources/images/tuto-prep/sr_moveit_hand_config_assistant7a.png) 
Double check when creating the single fingers group that you selected a kinematic solver. KDL at least should be there and this is the one to go with the biotac hand.

**Comment by sivammt** [comment] 2015-02-19 14:29
hand_ik_coupling_plugin & hand_kinematics plugin  are not available to me. I am able to use only kdl,pr2_arm and srv kinematics plugin. Should I create my own kinematics solver and integrate it with moveit ? can you help me getting the hand_ik_coupling _plugin and also could you send me a sample  kinematics.yaml generated for biotac

**Comment by guihomework** [comment] 2015-02-19 14:48
this coupling hand_ik_coupling_plugin is provided in the tutorial repository that you might have cloned, and hand_kinematics is the package available in the sr_contrib package of Shadow 
https://github.com/shadow-robot/sr-contrib in case you install it (this is the official plugin, the other one is a simplified version for the tutorial), and should be available to you if you source the workspace correctly. 
As said before, for the biotac hand you should not use the coupling IK but the KDL one. The Joint 1 of the shadow hand is blocked at 30 degrees with biotac sensors so there is no coupling involved. 
Once moveit setup assistant configured with IK solvers, the generate button should create a kinematics.yaml and it can be modified to integrate the position_only_ik : true (no graphical option in the wizard for that option)
Just a reminder, you can edit your moveit config as many time as you like with the moveit setup assistant launch file generated in a previous wizard call

example of kinematics.yaml
```
first_finger:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  position_only_ik: true
```

**Comment by sivammt** [comment] 2015-02-20 12:14
I got the hand_kinematics_plugin . I get an error while executing the biotac hand with hand_kinematics_plugin. I think my hand should work if I solve this error.
![screenshot from 2015-02-20 13 09 22](https://cloud.githubusercontent.com/assets/10954679/6285955/746e3b2c-b902-11e4-8bc2-4c4bb4b745e5.png)

**Comment by guihomework** [comment] 2015-02-20 16:21
if you are still running the biotac hand you must use KDL plugin, not hand_kinematics_plugin as said earlier.
otherwise tell me which hand you use and I will run it on my side.

**Comment by sivammt** [comment] 2015-02-20 16:56
ya i tried with kdl_plugin. It works. But i am not able to use the interactive markers in simulation. I think i am goin wrong somewhere.  I use the following urdf in my ros hydro version. I have even tried using it in indigo. but still it doesn't work. I just need to get that interactive marker in my biotac hand model. Thanks in advance
http://expirebox.com/download/8ad904786173f52e4dcef5c1b5ce8695.html

**Comment by guihomework** [comment] 2015-02-20 17:31
I uploaded a very basic example of the biotac moveit config on hydro. I followed the tutorial, just skipping the full hand and robot_pose steps. 
[file](https://raw.githubusercontent.com/wiki/guihomework/dexterous-manipulation-tutorial/media/examples/partial_biotac_moveit_config_hydro.tar.gz)

Please test it (roslaunch biotac_moveit_config/launch/demo.launch) and if it works, report what the differences were with your file so that I can improve the tutorial.

**Comment by sivammt** [comment] 2015-02-23 10:52
Thanks a lot for the file. It works. I have done a simple mistake and I couldn't find it before. While declaring joints for the biotac hand fingers, I thought neglecting joint J1 is sufficient (since it is a fixed joint) but in additional i have to neglect the biotac joint too. By doing this the interactive markers are visible. 
![siva](https://cloud.githubusercontent.com/assets/10954679/6326363/2e398606-bb51-11e4-9ad1-3a61adbc34ba.png)

As mentioned in the tutorial i tried moving the markers, but the finger of the hand doesn't move along with it. I used (position_only_ik: True) in the kinematics file for each finger. Still it doesn't work.

From the tutorial (This option does not solve the coupling issues in the last two finger joints (note: biotac hand has no coupling)) . what does the above statement mean? The shadow hand with biotac need not require coupling solver?

**Comment by guihomework** [comment] 2015-02-23 11:11
Thanks for the feedback.  The mixing of joints + chain declaration is indeed tricky and all the possible failure cases can hardly be explained in this tutorial.

**Please read this carefully** : as I said many times in my post, the **coupling solver** mentioned  in this tutorial is **NOT** for the **biotac** hand and must **NOT** be used. 

Your experiments made me discover that and the note I added means that because the biotac hand has no J1/J2 active couping (but a fixed joint which is as if there was no joint), the coupling solver must NOT be used, the KDL one should be used instead with the position_only_ik:true  

You should insist a little on placing the marker (maintain it and move it slowly in a reachable place), there are only a few positions were there is an actual IK solution (for KDL solver with position_only_ik:true).  Otherwise tick the "allow approximate IK solutions"

**Comment by sivammt** [comment] 2015-02-23 11:22
Thanks a lot for helping me throughout the simulation steps. I am able to move the fingers using the interactive markers. Your tutorial was really helpful. I need to move the fingers by passing commands through codes written through programming. Can you suggest me some tutorial or some samples for getting an idea on how to pass codes to control the movements of the fingers in the hand.

**Comment by guihomework** [comment] 2015-02-23 11:29
Thanks for testing the tutorial too and helping to improve it. 

I have not c++ or python code available yet for the hand that I can share with you, I would suggest going along this tutorial and adapting with the planning groups and end-effectors you just created.

http://docs.ros.org/hydro/api/pr2_moveit_tutorials/html/planning/src/doc/motion_planning_api_tutorial.html

I will close this discussion now as this is solved.

**Closed by guihomework** 2015-02-23 11:29 UTC

**Comment by sivammt** [comment] 2015-02-23 11:34
Ya thanks a lot.
